
spring:
  application:
    name: NFT-Market
  mvc:
    static-path-pattern: /static/**
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dinosaurMarket
server:
  port: 9090