spring:
  application:
    name: NFT-Market
  mvc:
    static-path-pattern: /static/**
  elasticsearch:
    uris: localhost:9200
  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8 #编码
    suffix: .html #模板后缀
    mode: HTML #模板
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: FBCD@dq1012
    url: jdbc:mysql://cd-cynosdbmysql-grp-rjsk3qca.sql.tencentcdb.com:24800/marketinfo
  data:
    mongodb:
      host: localhost
      port: 27017
      database: nft_market_info
logging:
  level:
    # 输出es的查询参数(调试用)
    tracer: TRACE
server:
  port: 9090
contract:
  network_url: HTTP://127.0.0.1:8545
  chain_id: 31337
  wallet_key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
  dfc_address: 0x5FbDB2315678afecb367f032d93F642f64180aa3
  market_address: 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
  dm_address: 0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0
  dem_address: 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9