
spring:
  application:
    name: NFT-Market
  mvc:
    static-path-pattern: /static/**
  elasticsearch:
    uris: http://localhost:9200/
logging:
  level:
    # 输出es的查询参数(调试用)
    tracer: TRACE
server:
  port: 9090

